import '@/lib/styles/globals.scss';

import { Metadata } from 'next';
import { Nunito } from 'next/font/google';

import { TheHeader } from '@/components/TheHeader';
import { Providers } from '@/components/utils/Providers';
import Scripts from '@/components/utils/scripts';

const inter = Nunito({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
  style: 'normal',
  fallback: ['Nunito', 'sans-serif'],
});

export const metadata: Metadata = {
  title: 'devOsa ➡️ TesTask for ABZ.Agancy',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Scripts />
        <Providers>
          <TheHeader />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
